os: linux
dist: focal
language: python

python:
  - "3.11"

services:
- mysql

branches:
  only:
  - develop

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install flake8
- pip install coveralls

before_script:
- flake8 edc_facility
- mysql -e 'create database edc character set utf8;'

script:
- coverage run --source=edc_facility manage.py test
- python manage.py check

after_success:
- coveralls
